spring:
  profiles:
    active: dev
  application:
    name: hr-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
#      配置路由
      routes:
        - id: payent_routh  #payment_route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 是否注册到Eureka服务器，server端禁用此选项
    register-with-eureka: true
    # 此客户端是否应从 eureka 服务器获取 eureka 注册表信息。 客户端服务需要拉取所有注册的信息用于rpc，但是作为注册服务器来说不需要此功能，本身就是注册中心了。
    fetch-registry: true
    service-url:
      # 服务注册地址
      defaultZone: http://${eureka.instance.hostname}:7001/eureka