spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.1.61:3306/lx_hr?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&useAffectedRows=true
    username: lianxin
    password: LX@789023234

  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 172.16.110.5
    # Redis服务器连接端口
    port: 6311
    # Redis服务器连接密码（默认为空）
    password: 3ulba65HHG7lprW
    # 连接超时时间（毫秒）
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  cloud:

hr:
  auth:
    exclude-path:
      - /login
      - /vcode/login
server:
  port: 8082

